version: '3.3'

services:
  rabbit:
    container_name: rabbit-container
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - vol_recitar:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  recitar_api:
    container_name: recitar-api
    depends_on:
      - db
      - rabbit
    build: .
    ports:
      - 8080:8080
    restart: always

volumes:
  vol_recitar: { }