spring:
  application:
    name: recitar-api

  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

  reports:
    model-path: /src/main/resources/report/
    model-filename: REC_MODEL_REPORT.docx

  output:
    ansi:
      enabled: always

api:
  security:
    token:
      secret: ${JWT_SECRET:my_secret}
    
    oauth:
      microsoft:
        token_url: ${RECITAR_TOKEN_URL}
        redirect_uri: ${RECITAR_REDIRECT_URI}
        client_id: ${RECITAR_CLIENT_ID}
        client_secret: ${RECITAR_CLIENT_SECRET}

# Loga debug
debug: true

# Setar essa variavel quando quiser que o log seja salvo em arquivo texto
#logging:
#  file:
#    path: C:\Users\victo\personal\git\recitar-api\src\main\resources\logs